package ProjectEuler;

//Problem 2 (Even Fibonacci Numbers)
/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
  By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

public class Problem2 {
    public static void main(String[] args) {
      int fnext=0,fprevious=2,fprevious2=1,i=1,sum=2; //Declare some variables
      while (fnext<4000000) {
        fnext=fprevious+fprevious2; //Get the current fib no. for this term
        fprevious2 = fprevious; //Update the new previous term for current fib no.
        fprevious = fnext;  //Update the new previous term with current fib no. for the next term's usage
        if (fnext%2==0) {
          sum = sum + fnext;
        }
        i++;
      }
      System.out.println(sum);
    }
}
